import 'package:career_coach/data/data_source/api_service.dart';
import 'package:career_coach/data/local/local_cache.dart';
import 'package:career_coach/data/remote/activity_remote.dart';
import 'package:career_coach/data/remote/auth_remote.dart';
import 'package:career_coach/data/remote/award_remote.dart';
import 'package:career_coach/data/remote/certificate_remote.dart';
import 'package:career_coach/data/remote/contact_information_remote.dart';
import 'package:career_coach/data/remote/education_remote.dart';
import 'package:career_coach/data/remote/favorite_remote.dart';
import 'package:career_coach/data/remote/goal_remote.dart';
import 'package:career_coach/data/remote/project_remote.dart';
import 'package:career_coach/data/remote/resume_remote.dart';
import 'package:career_coach/data/remote/skill_remote.dart';
import 'package:career_coach/data/remote/user_remote.dart';
import 'package:career_coach/data/remote/user_resume_remote.dart';
import 'package:career_coach/data/remote/work_experience_remote.dart';
import 'package:career_coach/data/repository_impl/activity_repository_impl.dart';
import 'package:career_coach/data/repository_impl/auth_repository_impl.dart';
import 'package:career_coach/data/repository_impl/award_repository_impl.dart';
import 'package:career_coach/data/repository_impl/certificate_repository_impl.dart';
import 'package:career_coach/data/repository_impl/contact_information_repository_impl.dart';
import 'package:career_coach/data/repository_impl/education_repository_impl.dart';
import 'package:career_coach/data/repository_impl/favorite_repository_impl.dart';
import 'package:career_coach/data/repository_impl/goal_repository_impl.dart';
import 'package:career_coach/data/repository_impl/project_repository_impl.dart';
import 'package:career_coach/data/repository_impl/resume_repository_impl.dart';
import 'package:career_coach/data/repository_impl/skill_repository_impl.dart';
import 'package:career_coach/data/repository_impl/user_repository_impl.dart';
import 'package:career_coach/data/repository_impl/user_resume_repository_impl.dart';
import 'package:career_coach/data/repository_impl/work_experience_repository_impl.dart';
import 'package:career_coach/domain/repository/activity_repository.dart';
import 'package:career_coach/domain/repository/auth_repository.dart';
import 'package:career_coach/domain/repository/award_repository.dart';
import 'package:career_coach/domain/repository/certificate_repository.dart';
import 'package:career_coach/domain/repository/contact_information_repository.dart';
import 'package:career_coach/domain/repository/education_repository.dart';
import 'package:career_coach/domain/repository/favorite_repository.dart';
import 'package:career_coach/domain/repository/goal_repository.dart';
import 'package:career_coach/domain/repository/project_repository.dart';
import 'package:career_coach/domain/repository/resume_repository.dart';
import 'package:career_coach/domain/repository/skill_repository.dart';
import 'package:career_coach/domain/repository/user_repository.dart';
import 'package:career_coach/domain/repository/user_resume_repository.dart';
import 'package:career_coach/domain/repository/work_experience_repository.dart';
import 'package:career_coach/domain/use_case/create_new_user_resume_copy_use_case.dart';
import 'package:career_coach/domain/use_case/create_new_user_resume_use_case.dart';
import 'package:career_coach/domain/use_case/delete_account_use_case.dart';
import 'package:career_coach/domain/use_case/get_activities_use_case.dart';
import 'package:career_coach/domain/use_case/get_awards_use_case.dart';
import 'package:career_coach/domain/use_case/get_certificates_use_case.dart';
import 'package:career_coach/domain/use_case/get_contact_information_use_case.dart';
import 'package:career_coach/domain/use_case/get_detail_user_resume_use_case.dart';
import 'package:career_coach/domain/use_case/get_educations_use_case.dart';
import 'package:career_coach/domain/use_case/get_favorites_use_case.dart';
import 'package:career_coach/domain/use_case/get_goal_use_case.dart';
import 'package:career_coach/domain/use_case/get_list_resume_use_case.dart';
import 'package:career_coach/domain/use_case/get_list_user_resume_recent_use_case.dart';
import 'package:career_coach/domain/use_case/get_list_user_resume_use_case.dart';
import 'package:career_coach/domain/use_case/get_profile_use_case.dart';
import 'package:career_coach/domain/use_case/get_projects_use_case.dart';
import 'package:career_coach/domain/use_case/get_skills_use_case.dart';
import 'package:career_coach/domain/use_case/get_work_experiences_use_case.dart';
import 'package:career_coach/domain/use_case/login_use_case.dart';
import 'package:career_coach/domain/use_case/logout_use_case.dart';
import 'package:career_coach/domain/use_case/register_use_case.dart';
import 'package:career_coach/domain/use_case/google_login_use_case.dart';
import 'package:career_coach/domain/use_case/github_login_use_case.dart';
import 'package:career_coach/domain/use_case/save_activities_use_case.dart';
import 'package:career_coach/domain/use_case/save_awards_use_case.dart';
import 'package:career_coach/domain/use_case/save_certificates_use_case.dart';
import 'package:career_coach/domain/use_case/save_contact_information_use_case.dart';
import 'package:career_coach/domain/use_case/save_educations_use_case.dart';
import 'package:career_coach/domain/use_case/save_favorites_use_case.dart';
import 'package:career_coach/domain/use_case/save_goal_use_case.dart';
import 'package:career_coach/domain/use_case/save_projects_use_case.dart';
import 'package:career_coach/domain/use_case/save_skills_use_case.dart';
import 'package:career_coach/domain/use_case/save_user_resume_use_case.dart';
import 'package:career_coach/domain/use_case/save_work_experiences_use_case.dart';
import 'package:career_coach/domain/use_case/update_avatar_use_case.dart';
import 'package:career_coach/domain/use_case/update_profile_use_case.dart';
import 'package:get_it/get_it.dart';

final getIt = GetIt.instance;

class DiConfig {
  static Future<void> init() async {
    // init
    await LocalCache.init();
    getIt.registerLazySingleton<ApiService>(() => ApiService());

    // remote
    getIt.registerLazySingleton<AuthRemote>(() => AuthRemote(getIt.get()));
    getIt.registerLazySingleton<UserRemote>(() => UserRemote(getIt.get()));
    getIt.registerLazySingleton<ResumeRemote>(() => ResumeRemote(getIt.get()));
    getIt.registerLazySingleton<UserResumeRemote>(() => UserResumeRemote(getIt.get()));
    getIt.registerLazySingleton<ContactInformationRemote>(() => ContactInformationRemote(getIt.get()));
    getIt.registerLazySingleton<GoalRemote>(() => GoalRemote(getIt.get()));
    getIt.registerLazySingleton<SkillRemote>(() => SkillRemote(getIt.get()));
    getIt.registerLazySingleton<ActivityRemote>(() => ActivityRemote(getIt.get()));
    getIt.registerLazySingleton<CertificateRemote>(() => CertificateRemote(getIt.get()));
    getIt.registerLazySingleton<AwardRemote>(() => AwardRemote(getIt.get()));
    getIt.registerLazySingleton<ProjectRemote>(() => ProjectRemote(getIt.get()));
    getIt.registerLazySingleton<WorkExperienceRemote>(() => WorkExperienceRemote(getIt.get()));
    getIt.registerLazySingleton<FavoriteRemote>(() => FavoriteRemote(getIt.get()));
    getIt.registerLazySingleton<EducationRemote>(() => EducationRemote(getIt.get()));

    // repository
    getIt.registerLazySingleton<AuthRepository>(() => AuthRepositoryImpl(getIt.get()));
    getIt.registerLazySingleton<UserRepository>(() => UserRepositoryImpl(getIt.get()));
    getIt.registerLazySingleton<ResumeRepository>(() => ResumeRepositoryImpl(getIt.get()));
    getIt.registerLazySingleton<UserResumeRepository>(() => UserResumeRepositoryImpl(getIt.get()));
    getIt.registerLazySingleton<ContactInformationRepository>(() => ContactInformationRepositoryImpl(getIt.get()));
    getIt.registerLazySingleton<GoalRepository>(() => GoalRepositoryImpl(getIt.get()));
    getIt.registerLazySingleton<SkillRepository>(() => SkillRepositoryImpl(getIt.get()));
    getIt.registerLazySingleton<ActivityRepository>(() => ActivityRepositoryImpl(getIt.get()));
    getIt.registerLazySingleton<CertificateRepository>(() => CertificateRepositoryImpl(getIt.get()));
    getIt.registerLazySingleton<AwardRepository>(() => AwardRepositoryImpl(getIt.get()));
    getIt.registerLazySingleton<ProjectRepository>(() => ProjectRepositoryImpl(getIt.get()));
    getIt.registerLazySingleton<WorkExperienceRepository>(() => WorkExperienceRepositoryImpl(getIt.get()));
    getIt.registerLazySingleton<FavoriteRepository>(() => FavoriteRepositoryImpl(getIt.get()));
    getIt.registerLazySingleton<EducationRepository>(() => EducationRepositoryImpl(getIt.get()));

    // use_case
    getIt.registerLazySingleton<RegisterUseCase>(() => RegisterUseCase(getIt.get()));
    getIt.registerLazySingleton<LoginUseCase>(() => LoginUseCase(getIt.get()));
    getIt.registerLazySingleton<GoogleLoginUseCase>(() => GoogleLoginUseCase(getIt.get()));
    getIt.registerLazySingleton<GitHubLoginUseCase>(() => GitHubLoginUseCase(getIt.get()));
    getIt.registerLazySingleton<LogoutUseCase>(() => LogoutUseCase(getIt.get()));
    getIt.registerLazySingleton<GetProfileUseCase>(() => GetProfileUseCase(getIt.get()));
    getIt.registerLazySingleton<UpdateAvatarUseCase>(() => UpdateAvatarUseCase(getIt.get()));
    getIt.registerLazySingleton<UpdateProfileUseCase>(() => UpdateProfileUseCase(getIt.get()));
    getIt.registerLazySingleton<DeleteAccountUseCase>(() => DeleteAccountUseCase(getIt.get()));
    getIt.registerLazySingleton<GetListResumeUseCase>(() => GetListResumeUseCase(getIt.get()));
    getIt.registerLazySingleton<GetListUserResumeRecentUseCase>(() => GetListUserResumeRecentUseCase(getIt.get()));
    getIt.registerLazySingleton<CreateNewUserResumeUseCase>(() => CreateNewUserResumeUseCase(getIt.get()));
    getIt.registerLazySingleton<CreateNewUserResumeCopyUseCase>(() => CreateNewUserResumeCopyUseCase(getIt.get()));
    getIt.registerLazySingleton<GetListUserResumeUseCase>(() => GetListUserResumeUseCase(getIt.get()));
    getIt.registerLazySingleton<GetDetailUserResumeUseCase>(() => GetDetailUserResumeUseCase(getIt.get()));
    getIt.registerLazySingleton<SaveUserResumeUseCase>(() => SaveUserResumeUseCase(getIt.get()));
    getIt.registerLazySingleton<GetContactInformationUseCase>(() => GetContactInformationUseCase(getIt.get()));
    getIt.registerLazySingleton<SaveContactInformationUseCase>(() => SaveContactInformationUseCase(getIt.get()));
    getIt.registerLazySingleton<GetGoalUseCase>(() => GetGoalUseCase(getIt.get()));
    getIt.registerLazySingleton<SaveGoalUseCase>(() => SaveGoalUseCase(getIt.get()));
    getIt.registerLazySingleton<GetSkillsUseCase>(() => GetSkillsUseCase(getIt.get()));
    getIt.registerLazySingleton<SaveSkillsUseCase>(() => SaveSkillsUseCase(getIt.get()));
    getIt.registerLazySingleton<GetActivitiesUseCase>(() => GetActivitiesUseCase(getIt.get()));
    getIt.registerLazySingleton<SaveActivitiesUseCase>(() => SaveActivitiesUseCase(getIt.get()));
    getIt.registerLazySingleton<GetCertificatesUseCase>(() => GetCertificatesUseCase(getIt.get()));
    getIt.registerLazySingleton<SaveCertificatesUseCase>(() => SaveCertificatesUseCase(getIt.get()));
    getIt.registerLazySingleton<GetAwardsUseCase>(() => GetAwardsUseCase(getIt.get()));
    getIt.registerLazySingleton<SaveAwardsUseCase>(() => SaveAwardsUseCase(getIt.get()));
    getIt.registerLazySingleton<GetProjectsUseCase>(() => GetProjectsUseCase(getIt.get()));
    getIt.registerLazySingleton<SaveProjectsUseCase>(() => SaveProjectsUseCase(getIt.get()));
    getIt.registerLazySingleton<GetWorkExperiencesUseCase>(() => GetWorkExperiencesUseCase(getIt.get()));
    getIt.registerLazySingleton<SaveWorkExperiencesUseCase>(() => SaveWorkExperiencesUseCase(getIt.get()));
    getIt.registerLazySingleton<GetFavoritesUseCase>(() => GetFavoritesUseCase(getIt.get()));
    getIt.registerLazySingleton<SaveFavoritesUseCase>(() => SaveFavoritesUseCase(getIt.get()));
    getIt.registerLazySingleton<GetEducationsUseCase>(() => GetEducationsUseCase(getIt.get()));
    getIt.registerLazySingleton<SaveEducationsUseCase>(() => SaveEducationsUseCase(getIt.get()));

    await getIt.allReady();
  }
}